package response

const (
	Fail = -1
	Ok = 0

	// 标签
	TAG_CREATED_FAILED = 601
	TAG_UPDATE_FAILED = 602
	TAG_NOT_FOUND = 603
	TAG_DELETE_FAILED = 604

	// 文章
	ARTICLE_CREATE_FAILED = 605
	ARTICLE_NOT_FOUND = 606
	ARTICLE_UPDATE_FAILED = 607
	ARTICLE_REPLACE_ASSOC_TAG_FALIED = 608
	ARTICLE_DELETE_FAILED = 609
	ARTICLE_CLEAR_ASSOCIATION_FAILED = 610
	ARTICLE_REPLACE_ASSOCIATION_ATTACHMENT_FAILED = 611
)
