basePath: /api/v1/
definitions:
  models.Tag:
    properties:
      createdAt:
        $ref: '#/definitions/util.JSONTime'
        type: object
      id:
        type: integer
      tagName:
        type: string
      tagStatus:
        type: integer
      updatedAt:
        $ref: '#/definitions/util.JSONTime'
        type: object
    type: object
  response.Failed:
    properties:
      code:
        example: -1
        type: integer
      msg:
        example: failed
        type: string
    type: object
  util.JSONTime:
    type: object
info:
  contact: {}
  description: 博客接口文档
  license: {}
  title: 博客接口文档
  version: "1.0"
paths:
  /tags:
    post:
      consumes:
      - application/json
      parameters:
      - description: 标签名称
        in: body
        name: tagName
        schema:
          type: string
      - description: 当前页码
        in: body
        name: page
        required: true
        schema:
          type: integer
      - description: 每页显示条数
        in: body
        name: pageSize
        required: true
        schema:
          type: integer
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Tag'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Failed'
      summary: 获取标签列表
swagger: "2.0"
