basePath: /api/v1/
definitions:
  http.Failed:
    properties:
      code:
        example: -1
        type: integer
      msg:
        example: failed
        type: string
    type: object
  models.Tag:
    properties:
      createdAt:
        $ref: '#/definitions/util.JSONTime'
        type: object
      id:
        example: 10
        type: integer
      tagName:
        example: php
        type: string
      tagStatus:
        example: 10
        type: integer
      updatedAt:
        $ref: '#/definitions/util.JSONTime'
        type: object
    required:
    - id
    type: object
  util.JSONTime:
    type: object
info:
  contact: {}
  description: 博客接口文档
  license: {}
  title: 博客接口文档
  version: "1.0"
paths:
  /tags:
    post:
      parameters:
      - description: 当前页码
        in: formData
        name: page
        type: integer
      - description: 每页显示条数
        in: formData
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Tag'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.Failed'
      summary: 获取标签列表
      tags:
      - Tag
swagger: "2.0"
